trigger:
  branches:
    include:
      - main

  paths:
    exclude:
      - '*.png'
      - README.md
      - '*.txt'

variables:
dockerRegistryServiceConnection = 'acr-service-connection'
acrLoginServer = 'myacrregistry20260413.azureacr.io'
tag = '$(Build.BuildId)'

stages:
  - stage: BuildAndPush
    displayName: 'Build Images'
    jobs:
      - job:
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Docker@2
            displayName: 'Build and Push Backend Image'
            inputs:
              containerRegistry: $(dockerRegistryServiceConnection)
              repository: 'backend'
              command: 'buildAndPush'
              Dockerfile: 'backend/Dockerfile'
              tags: $(tag)

          - task: Docker@2
            inputs:
              command: 'buildAndPush'
              Dockerfile: 'frontend/Dockerfile'
              repository: 'frontend'
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: $(tag)
            displayName: 'Build and Push Frontend Image'
