trigger:
  branches:
    include:
      - main

  paths:
    exclude:
      - '*.png'
      - README.md
      - '*.txt'

variables:
dockerRegistryServiceConnection = 'acr-service-connection'
acrHost = 'myacrregistry20260413.azureacr.io'
