apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weather-app-release
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # If your chart is in the 'helm' folder of ACR, use 'helm/weather-app'
      # If it's just at the root of ACR, use 'weather-app'
      chart: helm/weather-app 
      version: "1.0.*"
      sourceRef:
        kind: HelmRepository
        name: acr-oci-repo
        namespace: flux-system
  values:
    replicaCount: 1 # Keeping it low-cost for your B2s node