apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: acr-oci-repo
  namespace: flux-system
spec:
  interval: 5m
  type: oci
  url: oci://myacrregistry20260413.azurecr.io/helm/weather-app
  provider: azure